### ISSUE TITLE
`yieldfrom.Return` no longer works in Python 3.7+

### ISSUE THREAD

**Issue by starrify** [Nurdok/yieldfrom#4]
..when [PEP-479](https://www.python.org/dev/peps/pep-0479/) is fully applied.

Sample code (at c76eaec):

    Python 3.7.1 (default, Oct 22 2018, 10:41:28) 
    [GCC 8.2.1 20180831] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import yieldfrom
    >>> def foo():
    ...   yield 1
    ...   yieldfrom.Return(2)
    ... 
    >>> list(foo())
    Traceback (most recent call last):
      File "<stdin>", line 3, in foo
      File "/home/pengyu/temp/env/lib/python3.7/site-packages/yieldfrom.py", line 193, in Return
        raise StopIteration(return_value)
    StopIteration: 2

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    RuntimeError: generator raised StopIteration

**Comment by starrify** [comment]
Probably not an issue if this package is designed to be used with Python 2.x strictly, and not for writing version compatible code like when using `six`.

**Comment by Nurdok** [comment]
This package is explicitly designed to work for Python 2, as it backports the Python 3 `yield from` syntax. If you're using Python 3.7, you can just use `yield from` directly.

**Comment by Nurdok** [comment]
Oh, and by the way - how did you come to check this? Do you use `yieldfrom`? It would be interesting to hear if you do.

**Comment by starrify** [comment]
Thanks @Nurdok for the update. I totally agree that we shall have this issue ignored as this package seems to target to Python 2.x only. (And sorry for bothering you)

I was earlier writing some unit test which shall cover some special case related to PEP-380 and PEP-479. And I chose some not-so-good (and probably ugly and stupid :sweat_smile: ) approach for preparing the testing code for multiple versions (2.x, 3.x but not 3.7, and 3.7). Thus I wondered whether there's anyone that has already got something similar working. :D

**Comment by atyshka** [comment]
@Nurdok I'm confused... the readme states

>  It also supports Python 3.x so it can be used as compatibility library for code that supports both major versions of Python

But here your solution is to use the native 3.7 syntax? In that case, it seems that it cannot be used a compatibility library, and should only be used in pre-3.7 code. Can you clarify?

**Comment by Nurdok** [comment]
@atyshka the `README` was last updated 3 years ago. At that point, this library indeed supported Python 3.x. At this time, I'm not maintaining it anymore. If you'd like to send a PR to support the latest Python versions, I'll be happy to merge it.
