### ISSUE TITLE
Release 1.0.5

### ISSUE THREAD

**Issue by PaulRuvu** [Nurdok/yieldfrom#7]
Hi all,

I see the code is made Python3 compatible. Can a new release be expected anytime soon?

Regards,
Paul

**Comment by Nurdok** [comment]
Hi @PaulRuvu, sounds like a good idea. I'll try to do that in the next few days.

**Comment by Nurdok** [comment]
@PaulRuvu I released a new version. Enjoy :)

**Comment by PaulVerhoeckx** [comment]
@Nurdok Thanks a lot!
